GET http://localhost:5005/authors

###

GET http://localhost:5005/authors/5

###

POST http://localhost:5005/authors
Content-Type: application/json

{
  "Name": "Johnny Johnson"
}

###

PUT http://localhost:5005/authors/2
Content-Type: application/json

{
  "Name": "Harry Potter"
}

###

DELETE http://localhost:5005/authors/1

###

GET http://localhost:5005/genres

###

GET http://localhost:5005/genres/11

###

POST http://localhost:5005/genres
Content-Type: application/json

{
  "Name": "History"
}

###

PUT http://localhost:5005/genres/11
Content-Type: application/json

{
  "Name": "TEST"
}

###

DELETE http://localhost:5005/genres/11

###

GET http://localhost:5005/books

###

GET http://localhost:5005/books/2

###

POST http://localhost:5005/books
Content-Type: application/json

{
  "Title": "Harry Potter",
  "Author": "J.K. Rolling",
  "GenreId": 2
}

###

PUT http://localhost:5005/books/2
Content-Type: application/json

{
  "Title": "Star Wars",
  "Author": "George Lucas",
  "GenreId": 5
}

###

DELETE http://localhost:5005/books/3